In [1]:
import torch

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
# tensor can have dimensions more than 3 also!
# x = torch.empty(2) # 1-D tensor
# x = torch.empty(2,3,3) # 3-D tensor
x = torch.rand(2,3) # assigns random values to tensor
print(x)

tensor([[0.1721, 0.5395, 0.9012],
        [0.4968, 0.0361, 0.9279]])


In [3]:
# .size() to get size of the tensor
print(x.size())
print(x.dtype)

torch.Size([2, 3])
torch.float32


In [4]:
# to change the data type of tensor
y = torch.ones(2,2,dtype=torch.int) # initialise values with '1', which are of type int
print(y)
print(y.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [5]:
# to convert python list to tensor
z = torch.tensor([4.24,54.523])
print(z)

tensor([ 4.2400, 54.5230])


In [6]:
# imp. observation, values intialised as float numbers but dtype = int will conv them to int's
x = torch.tensor([4.24,54.523], dtype = int)
print(x)

tensor([ 4, 54])


/var/folders/0d/c32t51vs6yx8kjt9hjlrn_dh0000gn/T/ipykernel_1073/1352482510.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  x = torch.tensor([4.24,54.523], dtype = int)


In [7]:
# operations on tensors
y = torch.tensor([8,5], dtype = int)
z = x+y # or z = torch.add(x,y)
print(z)

# to add inplace
x.add_(y) # in pytorch, '_' represents inplace
print(x)

tensor([12, 59])
tensor([12, 59])


In [10]:
a = torch.rand(3,4)
print(a)
# to get only specific rows or cols
print(a[0, :]) # will get 0th row and all cols
print(a[:, 0]) # will get all rows and 0th col
print(a[1,2]) # will get an tensor at pos 0,0
# note that above will give tensor, to get value, we should use .item()
print(a[1,2].item())

tensor([[0.6202, 0.8169, 0.3346, 0.5410],
        [0.7715, 0.0595, 0.1404, 0.0991],
        [0.5864, 0.4738, 0.0378, 0.2274]])
tensor([0.6202, 0.8169, 0.3346, 0.5410])
tensor([0.6202, 0.7715, 0.5864])
tensor(0.1404)
0.1404159665107727


In [12]:
b = a.view(-1, 6) # 2-D tensor where cols will be 6 while rows will be determined auto.
print(b)
print(b.size())

tensor([[0.6202, 0.8169, 0.3346, 0.5410, 0.7715, 0.0595],
        [0.1404, 0.0991, 0.5864, 0.4738, 0.0378, 0.2274]])
torch.Size([2, 6])


In [14]:
import numpy as np

In [17]:
# numpy to tensor and vice versa
p = np.ones(4) # numpy arr
print(p)
print(type(p))
q = torch.from_numpy(p) # tensor from numpy arr
print(q)

r = 

[1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1.], dtype=torch.float64)


In [18]:
p = torch.ones(3) # tensor
print(p)
q = p.numpy()
print(q)
print(type(q))

tensor([1., 1., 1.])
[1. 1. 1.]
<class 'numpy.ndarray'>
